enum Unit {
  unidade,
  g,
  kg,
  mg,
  mcg,
  ml,
  l,
  colher,
  colherDeCha,
  colherDeSopa,
  xicara,
  pacote,
  caixa,
  frasco,
  ampola,
  tubo,
  barra,
  fatia,
  folha,
  pitada,
  outros;

  static Unit fromString(String value) {
    return switch (value) {
      'unidade' => Unit.unidade,
      'g' => Unit.g,
      'kg' => Unit.kg,
      'mg' => Unit.mg,
      'mcg' => Unit.mcg,
      'ml' => Unit.ml,
      'l' => Unit.l,
      'colher' => Unit.colher,
      'colher de chá' => Unit.colherDeCha,
      'colher de sopa' => Unit.colherDeSopa,
      'xícara' => Unit.xicara,
      'pacote' => Unit.pacote,
      'caixa' => Unit.caixa,
      'frasco' => Unit.frasco,
      'ampola' => Unit.ampola,
      'tubo' => Unit.tubo,
      'barra' => Unit.barra,
      'fatia' => Unit.fatia,
      'folha' => Unit.folha,
      'pitada' => Unit.pitada,
      'outros' => Unit.outros,
      _ => Unit.outros,
    };
  }

  String toJson() {
    return switch (this) {
      Unit.unidade => 'unidade',
      Unit.g => 'g',
      Unit.kg => 'kg',
      Unit.mg => 'mg',
      Unit.mcg => 'mcg',
      Unit.ml => 'ml',
      Unit.l => 'l',
      Unit.colher => 'colher',
      Unit.colherDeCha => 'colher de chá',
      Unit.colherDeSopa => 'colher de sopa',
      Unit.xicara => 'xícara',
      Unit.pacote => 'pacote',
      Unit.caixa => 'caixa',
      Unit.frasco => 'frasco',
      Unit.ampola => 'ampola',
      Unit.tubo => 'tubo',
      Unit.barra => 'barra',
      Unit.fatia => 'fatia',
      Unit.folha => 'folha',
      Unit.pitada => 'pitada',
      Unit.outros => 'outros',
    };
  }
}

enum Category {
  carnes,
  aves,
  peixesFrutosDoMar,
  laticinios,
  graosCereais,
  massas,
  legumes,
  verduras,
  frutas,
  temperosEspeciarias,
  oleosGorduras,
  docesSobremesas,
  bebidas,
  paesPanificacao,
  molhosCaldos,
  congelados,
  enlatados,
  farinhas,
  conservas,
  snacks,
  condimentos,
  cereaisMatinais,
  embutidos,
  confeitaria,
  produtosLimpeza,
  outros;

  static Category fromString(String value) {
    return switch (value) {
      'carnes' => Category.carnes,
      'aves' => Category.aves,
      'peixes e frutos do mar' => Category.peixesFrutosDoMar,
      'laticínios' => Category.laticinios,
      'grãos e cereais' => Category.graosCereais,
      'massas' => Category.massas,
      'legumes' => Category.legumes,
      'verduras' => Category.verduras,
      'frutas' => Category.frutas,
      'temperos e especiarias' => Category.temperosEspeciarias,
      'óleos e gorduras' => Category.oleosGorduras,
      'doces e sobremesas' => Category.docesSobremesas,
      'bebidas' => Category.bebidas,
      'pães e panificação' => Category.paesPanificacao,
      'molhos e caldos' => Category.molhosCaldos,
      'congelados' => Category.congelados,
      'enlatados' => Category.enlatados,
      'farinhas' => Category.farinhas,
      'conservas' => Category.conservas,
      'snacks' => Category.snacks,
      'condimentos' => Category.condimentos,
      'cereais matinais' => Category.cereaisMatinais,
      'embutidos' => Category.embutidos,
      'confeitaria' => Category.confeitaria,
      'produtos de limpeza' => Category.produtosLimpeza,
      'outros' => Category.outros,
      _ => Category.outros,
    };
  }

  String toJson() {
    return switch (this) {
      Category.carnes => 'carnes',
      Category.aves => 'aves',
      Category.peixesFrutosDoMar => 'peixes e frutos do mar',
      Category.laticinios => 'laticínios',
      Category.graosCereais => 'grãos e cereais',
      Category.massas => 'massas',
      Category.legumes => 'legumes',
      Category.verduras => 'verduras',
      Category.frutas => 'frutas',
      Category.temperosEspeciarias => 'temperos e especiarias',
      Category.oleosGorduras => 'óleos e gorduras',
      Category.docesSobremesas => 'doces e sobremesas',
      Category.bebidas => 'bebidas',
      Category.paesPanificacao => 'pães e panificação',
      Category.molhosCaldos => 'molhos e caldos',
      Category.congelados => 'congelados',
      Category.enlatados => 'enlatados',
      Category.farinhas => 'farinhas',
      Category.conservas => 'conservas',
      Category.snacks => 'snacks',
      Category.condimentos => 'condimentos',
      Category.cereaisMatinais => 'cereais matinais',
      Category.embutidos => 'embutidos',
      Category.confeitaria => 'confeitaria',
      Category.produtosLimpeza => 'produtos de limpeza',
      Category.outros => 'outros',
    };
  }
}
